@[if DEVELSPACE]@
export WALRUS_BOOTLOADER_HEX_FILE=@(CATKIN_DEVEL_PREFIX)/@(CATKIN_PACKAGE_SHARE_DESTINATION)/BootloaderCDC.hex
@[else]@
export WALRUS_BOOTLOADER_HEX_FILE=@(CMAKE_INSTALL_PREFIX)/@(CATKIN_PACKAGE_SHARE_DESTINATION)/BootloaderCDC.hex
@[end if]@
