boom:
  deploy_controller:
    type: effort_controllers/JointPositionController
    joint: walrus/boom/deploy_joint
    pid: {p : 0.0, i : 0.0, d : 0.0}
  pan_controller:
    type: effort_controllers/JointPositionController
    joint: walrus/boom/pan_joint
    pid: {p : 0.0, i : 0.0, d : 0.0}
  tilt_controller:
    type: effort_controllers/JointPositionController
    joint: walrus/boom/tilt_joint
    pid: {p : 0.0, i : 0.0, d : 0.0}
