boom:
  controllers: ['joint_state_controller', 'deploy_controller', 'pan_controller', 'tilt_controller']
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
